services:
  db:
    image: postgres:13
    container_name: 2025-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=hackathon
    networks:
      - hackathon-network
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data
networks:
  hackathon-network:
    driver: bridge
volumes:
  db-data:
