[build]
base = "/"
publish = "apps/docs/.next"
command = "pnpm i && pnpm exec playwright install && pnpm nx build docs"

[dev]
command = "pnpm nx dev docs"
publish = "apps/docs/.next"

[build.environment]
NODE_VERSION = "20.0.0"
