[build]
command = "pnpm i && pnpm remix vite:build apps/website"
publish = "apps/website/build/client"

[dev]
command = "pnpm remix vite:dev apps/website"
publish = "apps/website/build/client"

[[headers]]
for = "apps/website/build/*"

[headers.values]
Cache-Control = "public, max-age=31536000, s-maxage=31536000"

[build.environment]
NODE_VERSION = "20.0.0"
