[build]
command = "pnpm i && pnpm nx run website:build"
publish = "apps/website/public/build/index.js"

[[headers]]
for = "apps/website/build/*"

[headers.values]
Cache-Control = "public, max-age=31536000, s-maxage=31536000"

[build.environment]
NODE_VERSION = "20.0.0"
