name: Build

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]

    steps:
      - name: 🛎️ Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for all branches and tags to ensure the 'main' branch is available

      - name: Fetch main branch
        run: git fetch origin main:main # Explicitly fetch the 'main' branch to ensure it's available

      - name: List all branches
        run: git branch -a # Debugging step to list all branches fetched in the runner

      - name: 📦 Install pnpm
        uses: pnpm/action-setup@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Debug Git Status
        run: |
          git status  # Show the current branch and changes
          git branch -a  # List all local and remote branches
          git log -1  # Show the last commit for debug purposes

      - name: 🧹 Lint Projects
        # TODO: Restore functionality after pipeline is fixed
        run: pnpm i;
        # run: pnpm i; pnpm nx affected -t lint --base=origin/main --head=HEAD --verbose
        # Use 'origin/main' to reference the exact remote branch

      - name: 🏗️ Build Affected Projects
        run: pnpm nx affected -t build --base=origin/main --head=HEAD --verbose
        # Ensure the base is set to 'origin/main' to avoid any ambiguity about the branch

      - name: 💰 Profit
        run: echo 🐞
