name: End-to-End Tests

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'

jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]

    steps:
      - name: 🛎️ Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # All history for branches and tags

      - name: 📦 Install pnpm
        uses: pnpm/action-setup@v4
        # with:
        #   run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: 🎭 Install Playwright Browsers
        run: pnpm i; pnpm playwright install --with-deps

      - name: 💀 Run E2E Tests
        run: pnpm nx run-many -t e2e -p docs-e2e website-e2e portal-e2e --parallel=false --verbose

      - name: 📄 Upload Artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

      - name: 💰 Profit
        run: echo 🐞
